new html, js and css added
hseling/hseling-web-catandkittens pull request #2
Opened 2018-12-23 15:47 UTC by StanRed

2018-12-24 07:30 UTC, profitware requested changes

2018-12-24 07:30 UTC, profitware commented on src/web/static/main.js
> +var http = require('http');
Вот отсюда и далее — что это и зачем?

2018-12-24 07:30 UTC, profitware commented on src/web/templates/cat_collocations.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
Необходимо переделать на использование тега `{% static %}`

2018-12-24 07:30 UTC, profitware commented on src/web/templates/cat_collocations.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
И все дальнейшие относительные ссылки на стили и скрипты тоже

2018-12-24 07:30 UTC, profitware commented on src/web/templates/cat_check.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
Необходимо переделать на использование тега `{% static %}` и все дальнейшие ссылки на стили и скрипты тоже

2018-12-24 18:07 UTC, StanRed commented on src/web/templates/cat_collocations.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
Сделал.

2018-12-24 18:07 UTC, StanRed commented on src/web/templates/cat_check.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
Готово.

2018-12-24 18:08 UTC, StanRed commented on src/web/static/main.js
> +var http = require('http');
Убрал лишний код из старых версий. DataTable нужен для активации возможности сортировки по содержимому в таблице.

2018-12-24 20:34 UTC, profitware requested changes

2018-12-24 20:34 UTC, profitware commented on src/web/templates/cat_check.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
Здесь пока не видно — до сих пор относительные

2018-12-24 21:15 UTC, profitware commented on src/web/templates/cat_check.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
@StanRed

2018-12-25 06:28 UTC, StanRed commented on src/web/templates/cat_check.html
> +    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
Исправил.

2019-01-08 20:57 UTC, profitware approved these changes

2019-01-08 20:57 UTC, merged